export const MAP_ERROR_1 = '地图文件加载失败'
export const MAP_ERROR_2 = '进入未知地图'
export const MAIN_EXIT_0010 = '到达指定地图'
export const MAIN_EXIT_0020 = '复活'
export const MAIN_EXIT_0030 = '回收装备'
export const MAIN_EXIT_0031 = '背包满了'
export const OK = 'ok'